#!/usr/bin/env bun

import { $ } from "bun";
import { join } from "path";
import { readdir } from "fs/promises";

const ROOT = import.meta.dir;

console.log("Building Knotes...\n");

// Step 1: Build frontend
console.log("1. Building frontend...");
await $`cd ${join(ROOT, "src/web/app")} && bun run build`.quiet();
console.log("   Frontend built.\n");

// Step 2: Generate embedded assets module
console.log("2. Embedding frontend assets...");
const distDir = join(ROOT, "src/web/app/dist");
const assets: Record<string, { content: string; mime: string }> = {};
const mimeTypes: Record<string, string> = {
  html: "text/html",
  js: "application/javascript",
  css: "text/css",
  json: "application/json",
  svg: "image/svg+xml",
  png: "image/png",
  ico: "image/x-icon",
};

async function collectFiles(dir: string, prefix: string) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    const urlPath = prefix + entry.name;
    if (entry.isDirectory()) {
      await collectFiles(fullPath, urlPath + "/");
    } else {
      const ext = entry.name.split(".").pop() || "";
      const content = await Bun.file(fullPath).text();
      assets["/" + urlPath] = {
        content,
        mime: mimeTypes[ext] || "application/octet-stream",
      };
    }
  }
}

await collectFiles(distDir, "");

const assetsModule = `// Auto-generated by build.ts — do not edit
export const embeddedAssets: Record<string, { content: string; mime: string }> = ${JSON.stringify(assets)};
`;
await Bun.write(join(ROOT, "src/web/embedded-assets.ts"), assetsModule);
console.log(`   Embedded ${Object.keys(assets).length} files.\n`);

// Step 3: Compile standalone binary
console.log("3. Compiling standalone binary...");
// node-llama-cpp has platform-specific optional deps that can't all resolve.
// Mark them as external — they're dynamically imported and only the right
// platform's package is needed at runtime.
const externalPkgs = [
  "@node-llama-cpp/mac-arm64-metal",
  "@node-llama-cpp/mac-x64",
  "@node-llama-cpp/win-x64",
  "@node-llama-cpp/win-x64-cuda",
  "@node-llama-cpp/win-x64-cuda-ext",
  "@node-llama-cpp/win-x64-vulkan",
  "@node-llama-cpp/win-arm64",
];
const externalArgs = externalPkgs.flatMap((pkg) => ["--external", pkg]);
await $`bun build --compile ${join(ROOT, "src/main.ts")} --outfile ${join(ROOT, "dist/knotes")} --minify ${externalArgs}`.quiet();
console.log("   Binary compiled to dist/knotes\n");

// Step 4: Clean up generated assets module
await Bun.write(join(ROOT, "src/web/embedded-assets.ts"), `// Generated at build time — run build.ts to populate
export const embeddedAssets: Record<string, { content: string; mime: string }> = {};
`);

console.log("Done! Run: ./dist/knotes --help");
